// app-solid/src/Calc.tsx
import { createSignal, createEffect } from 'solid-js';

export function Calc() {
  const [a, setA] = createSignal(1);
  const [b, setB] = createSignal(8);
  const [c, setC] = createSignal(3);
  const [d, setD] = createSignal(4);
  
  createEffect(() => {
    setA(b() + c());
  });

  createEffect(() => {
    setD(a() * 2);
  });

  createEffect(() => {
    if (a() > 10) {
			console.log('resetting');
			setB(0);
      setC(0);
		}
  });

  createEffect(() => {
    console.log({ a:a(), b:b(), c:c(), d:d() })
  });

  return <></>;
}

// app-react/src/component/Calc.tsx
import { useState, useEffect } from 'react';

export const Calc = () => {
  const [a, setA] = useState(1);
  const [b, setB] = useState(8);
  const [c, setC] = useState(3);
  const [d, setD] = useState(4);
  
  useEffect(() => {
    setA(b + c);
  }, [b, c]);

    useEffect(() => {
    setD(a * 2);
  }, [a]);

  useEffect(() => {
    if (a > 10) {
			console.log('resetting');
			setB(0);
      setC(0);
		}
  }, [a]);

  useEffect(() => {
    console.log({ a, b, c, d })
  }, [a,b,c,d]);

  return <div />;
}
