// app-svelte/src/lib/State4.svelte
<script lang="ts">
  import { writable } from "svelte/store";
  import { onDestroy } from "svelte";

  let componentValue = 0;
  let storeValue = writable(0);
  const handleStoreClick = () => {
    storeValue.update((prev) => prev + 1);
    // Unable to access store value synchronously, requires subscribe
  };

  const handleComponentClick = () => {
    componentValue = componentValue + 1;
    console.log("component click", componentValue);
  };

  $: console.log("component effect", componentValue);

  const unsubscribe = storeValue.subscribe((value) => {
    console.log("store effect", value);
  });

  onDestroy(() => unsubscribe());
</script>

<div>
  <button on:click={handleStoreClick}>Click store</button>
  <button on:click={handleComponentClick}>Click component</button>
  <div>component: {componentValue}</div>
  <div>store: {$storeValue}</div>
</div>

// app-solid/src/State4.tsx
import { createEffect, createSignal } from "solid-js";
import { createStore } from "solid-js/store";

export const State4 = () => {
  const [componentValue, setComponentValue] = createSignal<number>(0)
  const [storeValue, setStoreValue] = createStore<{value: number}>({value: 0});

  const handleStoreClick = () => {
    setStoreValue({value: storeValue.value + 1})
    console.log('store click', storeValue.value);
  }

  const handleComponentClick = () => {
    setComponentValue(componentValue() + 1)
    console.log('component click', componentValue());
  }

  createEffect(() => console.log('store effect', storeValue.value));
  createEffect(() => console.log('component effect', componentValue()))

  return <div>
    <button onClick={handleStoreClick}>Click store</button>
    <button onClick={handleComponentClick}>Click component</button>
  </div>
}
