// app-react/src/component/State2.tsx
import { useEffect, useState } from "react";

export const State2 = () => {
  const [count, setCount] = useState(0);
  const [isSmallerThan10, setIsSmallerThan10] = useState(true);
  useEffect(() => {
    if (count < 10) {
      console.log("smaller", count);
      setCount(11);
    } else {
      console.log("larger", count);
      setIsSmallerThan10(false);
    }
  }, [count, setCount, setIsSmallerThan10]);

  return null;
};

// app-solid/src/State2.tsx
import { createEffect, createSignal } from "solid-js";

export const State2 = () => {
  const [count, setCount] = createSignal(0);
  const [isSmallerThan10, setIsSmallerThan10] = createSignal(true);

  createEffect(() => {
    if (count() < 10) {
      console.log("smaller", count());
      setCount(11);
    } else {
      console.log("larger", count());
      setIsSmallerThan10(false);
    }
  });

  return null;
};
